// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBa3Kk44UTqYp8--N9zM_cMe4DeNpLgTHY',
    appId: '1:474166270054:web:125939c8dc72f5598975a7',
    messagingSenderId: '474166270054',
    projectId: 'attendance-8a192',
    authDomain: 'attendance-8a192.firebaseapp.com',
    storageBucket: 'attendance-8a192.firebasestorage.app',
    measurementId: 'G-F2SJPKZ79Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjcEr7mph-oFTcTM8xpSD01UtkQs9ld0o',
    appId: '1:474166270054:android:eda221c61c3aa49b8975a7',
    messagingSenderId: '474166270054',
    projectId: 'attendance-8a192',
    storageBucket: 'attendance-8a192.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEmBSXSjFRbGG-y5nqkVGEzaKrZANtONs',
    appId: '1:474166270054:ios:06afc27fc8816ed18975a7',
    messagingSenderId: '474166270054',
    projectId: 'attendance-8a192',
    storageBucket: 'attendance-8a192.firebasestorage.app',
    iosBundleId: 'com.example.supportticket',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAEmBSXSjFRbGG-y5nqkVGEzaKrZANtONs',
    appId: '1:474166270054:ios:06afc27fc8816ed18975a7',
    messagingSenderId: '474166270054',
    projectId: 'attendance-8a192',
    storageBucket: 'attendance-8a192.firebasestorage.app',
    iosBundleId: 'com.example.supportticket',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBa3Kk44UTqYp8--N9zM_cMe4DeNpLgTHY',
    appId: '1:474166270054:web:00c2b1bdfc9dd1c18975a7',
    messagingSenderId: '474166270054',
    projectId: 'attendance-8a192',
    authDomain: 'attendance-8a192.firebaseapp.com',
    storageBucket: 'attendance-8a192.firebasestorage.app',
    measurementId: 'G-FT93RWQ0EW',
  );
}
